### ISSUE TITLE
how can I add a second monitor without being detected in multiple display check?

### ISSUE THREAD

**Issue by AHMED-ETO** [imm0r/hideProcess#1]
I saw it on someone's computer. He'd connected a second monitor. but when I tried to detect it in multiple display setting, it did not show the second monitor. I also checked it in "Project" section by pressing Windows+P , again it showed " PC Only". The second monitor was there and working, but was kind of hidden and not detectable.
How could he do it? is it by using an passive VGA splitter? or is there a program to be installed Can you help me with that

**Comment by imm0r** [comment]
Sorry but no I am not able to help you. First of all your "issue" has absolutly nothing to do with this repository or anything related to me or my projects. And second what the heck are you talking about?!
